# Global Options
plugins:
  - jekyll-seo-tag
  - jekyll-sitemap
  - jekyll-redirect-from
future: true
permalink: pretty
timezone: "-600"
google_analytics: "UA-111929567-1"
# SEO / Sitemap
url: "http://trade-school.co"
baseurl: ""
title: "TRADE SCHOOL | July 23-26, 2018 | Denver, CO"
description: "Five days of art and talks exploring the nature of work, set against the backdrop of North America’s largest gathering of outdoor industry leaders"
current_edition: "summer-2018"
location_address: "Aloft Hotel, 800 15th St, Denver, CO"
twitter:
  username: somethingindpnt
facebook:
  publisher: https://www.facebook.com/SomethingIndependent/
social:
  name: TRADE SCHOOL, a Something Independent project
  links:
    - https://twitter.com/somethingindpnt
    - https://www.facebook.com/SomethingIndependent/
    - https://www.instagram.com/somethingindependent/
logo: assets/trade-school-ig.jpg
# Collections
collections:
  talks:
    output: true
defaults:
  - scope:
      path: ""
    values:
      image: assets/trade-school-ig.jpg
      last_modified_at: now
  - scope:
      path: ""
      type: talks
    values:
      layout: talk
  - scope:
      path: "_talks/winter-2018"
      type: talks
    values:
      edition: "winter-2018"
  - scope:
      path: "_talks/summer-2018"
      type: talks
    values:
      edition: "summer-2018"
