---
new_page_extension: md
auto_deploy: false
admin_path: 
webhook_url: 
collections:
- path: _posts
  label: Posts
  create: all
- path: _talks
  label: Talks
  create: all
  default_front_matter_template: talks
- path: _talks/summer-2018
  label: Talks - Summer 2018
  create: all
  default_front_matter_template: talks-summer-2018
- path: _talks/winter-2018
  label: Talks - Winter 2018
  create: all
  default_front_matter_template: talks-winter-2018
- path: ''
  label: Pages
  create: all
upload_dir: assets
public_path: "/assets"
front_matter_path: ''
use_front_matter_path: false
file_template: ":filename:"
