---
label: default
hide_body: false
is_partial: false
fields:
- name: image
  label: Image
  type: text
  hidden: false
  default: assets/trade-school-ig.png
- name: last_modified_at
  label: Last modified at
  type: text
  hidden: false
  default: now
